export const LOGIN = "LOGIN";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const DETAILS = "DETAILS";
export const DETAILS_START = "DETAILS_START";
export const DETAILS_SUCCESS = "DETAILS_SUCCESS";
export const DETAILS_FAILURE = "DETAILS_FALIURE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const STAFF_MEMBERS = "STAFF_MEMBERS";
export const STAFF_MEMBERS_START = "STAFF_MEMBERS_START";
export const STAFF_MEMBERS_SUCCESS = "STAFF_MEMBERS_SUCCESS";
export const STAFF_MEMBERS_FAILURE = "STAFF_MEMBERS_FAILURE";

export const DISABLE_STAFF = "DISABLE_STAFF";
export const DISABLE_STAFF_START = "DISABLE_STAFF_START";
export const DISABLE_STAFF_SUCCESS = "DISABLE_STAFF_SUCCESS";
export const DISABLE_STAFF_FAILURE = "DISABLE_STAFF_FAILURE";

export const ENABLE_STAFF = "ENABLE_STAFF";
export const ENABLE_STAFF_START = "ENABLE_STAFF_START";
export const ENABLE_STAFF_SUCCESS = "ENABLE_STAFF_SUCCESS";
export const ENABLE_STAFF_FAILURE = "ENABLE_STAFF_FAILURE";

export const ADD_STAFF = "ADD_STAFF";
export const ADD_STAFF_START = "ADD_STAFF_START";
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const ADD_STAFF_FAILURE = "ADD_STAFF_FAILURE";
